/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置以获得 + ",
    "Difficulty up for": "难度提升以获得",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Upgrades": "升级",
    "Challenges": "挑战",
    "Buyables": "购买项",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    //马造2树文本
    "Coin is the basic resource in 2D Mario game.": "金币是2D马力欧游戏的基础资源",
    "It never has been changed!": "它从未被改变！",
    "Super Mushroom upgrades are stronger!": "超级蘑菇升级更强",
    "Super Mushroom is a kind of Power-ups, first appearance is in SMB1 (1985, FC/NES).": "超级蘑菇是一种力量升级，它的第一次出现在《超级马力欧兄弟1》(1985, FC/NES)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "MeT": "MeT",
    "YuC'e": "YuC'e",
    "Re": "Re",
    "QiV": "QiV",
    "SUS": "SUS",
    "Scientific": "科学",
    "Standard": "标准",
    "BEAF": "BEAF阵列",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程",
    "Hyper-E": "超-E",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏（通用）
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '新游戏',
    'Keep Going': '继续游戏',
    'The Modding Tree Discord': '模组树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模组树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水蓝',
    'emerald': '绿宝石',
    'castle': '城堡',
    'galaxy': '星系',
    'wonderful': '惊奇',
    'athletic': '天空',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'v8': 'v8',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //马造2树游戏内容
    "Cleared Courses": "通过的关卡数",
    "Currencies": "资源",
    "Pink Key Coins": "粉红金币",
    "Rotten Mushroom": "腐烂蘑菇",
    "Bouncy Ball": "弹力球",
    "Destruction": "破坏",
    "SL Skill Tree": "超级叶子技能树",
    "Cape Essence": "斗篷精华",
    "Yoshi": "耀西",
    "Yoshi Effect": "耀西效果",
    "Super Bell Dimensions": "超级铃铛维度",
    "Characters' Box": "角色箱子",
    "Link's Bomb": "林克炸弹",
    "Temples": "神庙",
    "Hyrule Shield": "海拉鲁盾",
    "Link's Bow": "林克的弓",
    "Container": "容器",
    "Grabbing": "抓取",
    "Swimming": "游泳",
    "Balloon Expansion": "气球膨胀",
    "SMM2 Fly All-stars": "马造2飞行道具全明星",
    "SA Overpowers": "超级橡栗超强化",
    "Boomerang": "回旋镖",
    "Mario's Journey": "马力欧的旅程",
    "Luigi's Journey": "路易吉的旅程",
    "Toad's Journey": "奇诺比奥的旅程",
    "Rewards": "奖励",
    "Toad Level": "奇诺比奥等级",
    "Toad Tier": "奇诺比奥阶层",
    "Toad Tetr": "奇诺比奥四重阶层",
    "Toad Pent": "奇诺比奥五重阶层",
    "Toad Hex": "奇诺比奥六重阶层",
    "Higher Toad Tier Layers": "更高的奇诺比奥阶层重数",
    "Awaken": "觉醒",
    "Toadette's Journey": "奇诺比珂的旅程",
    "No Damage Challenge": "无伤挑战",
    "Free Clears": "立刻过关关卡",
    "One Shot Clears": "一命通过关",
    "Auto and Condition Courses": "自动/条件关卡",
    "Koopaling Bosses": "酷霸七人众",
    "Battles": "战斗",
    "Minigames": "小游戏",
    "Boss Rush and Flaw": "Boss连战和瑕疵",
    "Lava": "熔岩",
    "Poison": "毒液",
    "More Bosses": "更多Boss",
    "Boom Boom": "奔奔",
    "Poom Poom": "碰碰",
    "Pow Block": "POW砖块",
    "Check Point": "中间点",
    "VS Rating Stats": "对战积分统计",
    "Researches": "研究",
    "VS Skills": "对战技能",
    "Lag": "卡顿",
    "Batoko": "四人图",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线进度: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "游戏时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "记数法: ",
    "Show Endgame (Spoiler)": "显示版本终点（含剧透）",
    "Maximum OoMs in Commas (Not affact all notations)": "用逗号显示数量级（并非在所有记数法有效）",
    "Currently: ": "当前：",
    "Completions: ": "完成次数：",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " (Before Bonus Levels)": "（奖金等级之前）",
    " ^ Floor(log10(Plants))": " ^ Floor(log10(植物))",
    "(softcapped)": "（受软上限限制）",
    
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\÷([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)e([\d\.,]+)$/,
    /^\÷([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^价格(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^×\/\÷([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\(([\d\.,]+) OoMs$/,
    /^\$([\d\.,]+)$/,
    /^\÷([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^×\/\÷([\d\.,]+)$/,
    /^x([\d\.,]+)$/,
    /^xe([\d\.,]+)$/,
    /^÷e([\d\.,]+)$/,
    /^e([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^×\/\÷([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/,
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^Pink Key Coins, multiplying Coin gain by$/,'粉红金币，加成金币获取'],
    [/^You have (.+) Cleared Courses$/, '你有 $1 通过的关卡数'],
    [/^Your best amount of coin is (.+)$/, '你最多拥有 $1 金币'],
    [/^Softcap starts at (.+) Coins$/, '软上限开始于 $1 金币'],
    [/^Fragments of the key$/, '钥匙碎片'],
    [/^No key touching challenge in SM3DW$/, '3D世界不摸钥匙挑战'],
    [/^Keys are in bubbles$/, '泡泡中的钥匙'],
    [/^Multiply (.+) Pink Key Coin every level.$/, '每级将粉红金币获取变为 $1x'],
    [/^Level: (.+)$/, '等级：$1'],
    [/^Effect: (.+)$/, '当前效果：$1'],
    [/^Cost: (.+) Pink Key Coins$/, '价格：$1 粉红金币'],
    [/^Cost: (.+) Coins$/, '价格：$1 金币'],
    [/^Reach (.+) coins$/, '获得 $1 金币'],
    [/^Reach (.+) cleared courses$/, '获得 $1 通过的关卡数'],
    [/^Reach (.+) coins \(Overpowered\)$/, '获得 $1 金币（已超强化）'],
    [/^Reach (.+) cleared courses \(Overpowered\)$/, '获得 $1 通过的关卡数（已超强化）'],
    [/^It begins!$/, '开始了！'],
    [/^Triple your cleared courses gain.$/, '将通过的关卡数获取变为3倍'],
    [/^Here are more coins!$/, '这里有更多金币'],
    [/^Multiply cleared courses gain based on your current coins.$/, '金币加成通过的关卡数获取'],
    [/^Coin reward room$/, '金币奖励房'],
    [/^Multiply cleared courses gain based on theirselves.$/, '金币加成自身'],
    [/^You need a power-up!$/, '你需要力量升级！'],
    [/^Faster and faster$/, '越来越快'],
    [/^Multiply cleared courses gain based on theirselves.$/, '通过的关卡数加成自身'],
    [/^From coins to 1-ups$/, '从金币到1UP'],
    [/^Multiply coin gain based on super mushrooms.$/, '超级蘑菇加成金币获取'],
    [/^Coin pool$/, '金币池'],
    [/^20x coin gain$/, '金币获取变为20x'],
    [/^Lakitu throws coins$/, '球盖姆丢出金币'],
    [/^100x coin gain$/, '金币获取变为100x'],
    [/^Bullet launches coins$/, '炮台发射金币'],
    [/^2024x coin gain$/, '金币获取变为2024x'],
    [/^Red pipe generates coins$/, '红色水管产生金币'],
    [/^(.+) coin gain and unlock 5th super mushroom upgrade$/, '$1金币获取并且解锁第5超级蘑菇升级'],
    [/^Key door$/, '钥匙门'],
    [/^Start to generate 1 pink key coin every second.$/, '开始产生1粉红金币每秒'],
    [/^Key door trolls are bad$/, '出门杀很糟糕'],
    [/^Unlock the 2nd coin buyable.$/, '解锁第2个金币购买项'],
    [/^P switches affect coins$/, 'P开关影响金币'],
    [/^More coins and more fire\?$/, '更多金币和火焰？'],
    [/^100x Coin and Pink Key Coin gain$/, '金币和粉红金币的获取变为100x'],
    [/^Gain more Fire Flower based on coins with a weak effect.$/, '金币加成火之花获取，但是效果弱化'],
    [/^Automate mushrooms$/, '自动蘑菇'],
    [/^Passive gain 100% Super Mushroom every second and unlock more Fire Flower upgrades.$/, '每秒被动获取100%的超级蘑菇，解锁更多火之花升级'],
    [/^x2.5 your coins gain.$/, '金币获取变为2.5x'],
    [/^Overpowered effect: Delay 2nd Coin upgrade's softcap by \^25.$/, '超强化效果：延迟第2金币升级的软上限到原来的^25'],
    [/^Overpowered effect: You start every reset with (.+) Coins.$/, '超强化效果：每次重置你将自带$1金币'],
    [/^Triple coin gain.$/, '三倍金币获取'],
    [/^Unlock a super mushroom challenge.$/, '解锁一个超级蘑菇挑战'],
    [/^Cleared courses gain x1e50.$/, '通过的关卡数获取变为1e50x'],
    [/^I'm stronger!$/, '我被强化了！'],
    [/^Multiply cleared courses gain based on super mushrooms.$/, '超级蘑菇加成通过的关卡数获取'],
    [/^Be able to break normal bricks$/, '能够破坏普通砖块'],
    [/^x1.5 super mushroom gain and unlock more coin upgrades.$/, '1.5x超级蘑菇获取，解锁更多金币升级'],
    [/^Jump on the enemies!$/, '在敌人上跳跃！'],
    [/^Multiply cleared courses gain based on time spent on this super mushroom reset.$/, '在这次超级蘑菇重置的时间加成通过的关卡数获取'],
    [/^Life farming$/, '刷命'],
    [/^Challenge Goomba's base is 15 now.$/, '挑战 栗宝宝 的效果基数现在变为15'],
    [/^You need a stronger power-up, right\?$/, '你需要一个更强的力量提升，对吗？'],
    [/^Unlock a new layer$/, '解锁新的层级'],
    [/^Reach (.+) super mushrooms$/, '获得$1超级蘑菇'],
    [/^Reach (.+) super mushrooms \(Overpowered\)$/, '获得$1超级蘑菇 （已超强化）'],
    [/^Gain coins 100% of your reset every second passively.$/, '每秒被动获取100%重置获得的金币'],
    [/^Super mushroom resets nothing.$/, '获得超级蘑菇不再进行重置'],
    [/^999-coin clear condition$/, '999金币的条件'],
    [/^Multiply 1e10 cleared courses every level.$/, '每级将通过的关卡数获取变为1e10x'],
    [/^Goombas$/, '栗宝宝'],
    [/^Square root cleared courses gain$/, '通过的关卡数获取变为^0.5'],
    [/^5000\/25000000\/1.25e11 cleared courses for 1st\/2nd\/3rd completion$/, '5000/25000000/1.25e11通过的关卡数在第1/2/3完成次数'],
    [/^Overpowered effect: Boost Boomerang gain based on Super Mushroom.$/, '超强化效果：超级蘑菇加成回旋镖获取'],
    [/^Reward: Decuple\(10x\) super mushroom gain per every completion.$/, '奖励：每完成一次使超级蘑菇获取翻10倍'],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    [/^$/, ''],
    //容易把其他汉化文本覆盖的
    [/^$/, ''],
    /* 来源：植物树汉化文件
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) plants$/, '你有 $1 植物'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) trees$/, '你有 $1 树'],
    [/^You Have (.+) Fish.$/, '你有 $1 鱼。'],
    [/^You Have (.+) Ecology$/, '你有 $1 生态'],
    [/^Garden Costs (.+) and Unlock a New Fish Upgrade. Shift to see Details$/, '花园成本 $1 并解锁新的鱼类升级。按下 Shift 查看详细信息'],
    [/^Points \^ N where N is X \÷ (.+). Currently: (.+)$/, '点数 \^ N where N is X \÷ $1. 当前: $2'],
    [/^(.+) \^ (.+) \= (.+), (.+) \= (.+) and (.+)$/, '$1 \^ $2 = $3, $4 = $5 和 $6'],
    [/^(.+)\/sec. You have (.+) Leaves, Dividing Tree Requirements by (.+).$/, '$1\/秒。您有 $2 树叶，将树需求除以 $3。'],
    [/^by (.+). Trees are Affected by the 1st Garden Milestone. You have (.+) Leaves, Dividing Tree Requirements by (.+).$/, '$1。树木受到第一个花园里程碑的影响。您有 $2 树叶，将树木需求除以 $3。'],
    [/^If you wrote (.+) digits per second, it would take you approximately (.+) seconds to write down your time spent researching.$/, '如果您每秒写 $1 位数字，则大约需要 $2 秒才能写下您花在研究上的时间。'],
    [/^Multiply Research Time Gain by (.+). Hold to buy max.$/, '将研究时间收益乘以 $1。按下购买最大。'],
    [/^Divide Research Requirement by (.+). Hold to buy max.$/, '将研究要求除以 $1。按下购买最大。'],
    [/^Plant costs (.+) and Unlock a New Garden Upgrade. Shift to see Details$/, '植物成本 $1 并解锁新的花园升级。移至查看详细信息'],
    [/^You have made a total of (.+) Reclaimed Ecosystems$/, '您总共创建了 $1 回收的生态系统'],
    [/^Generate Ecology and Lose (.+)\/sec. Currently: (.+)\/sec$/, '生成生态并损失 $1\/秒. 目前: $2\/秒'],
    [/^Multiply Leaf Gain by (.+) \((.+)s\).$/, '将叶子增益乘以 $1（$2 秒）。'],
    [/^Multiply Point Gain by (.+) \((.+)s\).$/, '将点数增益乘以 $1（$2 秒）。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You are generating (.+) Wildlife every second. You keep Wildlife Upgrades on reset. You have (.+) Larger Wildlife which is Multiplying Point gain by (.+) and Wildlife gain by (.+).$/, '你每秒生成 $1 野生动物。你重置时保留野生动物升级。你有 $2 更大的野生动物，即乘以点数 $3 和野生动物增益 $4。'],
    [/^(.+) Plants \-\> (.+) Plants$/, '1.5rt 植物 \-\> 1.1rt 植物'],
    [/^Find Researchers to help. Researchers Multiply Research Gain by Researchers \+ (.+). You have (.+) Researchers. Hold to buy max.$/, '寻找研究人员来帮助。研究人员将研究增益乘以研究人员 \+ $1。您有 $2 个研究人员。按下购买最大。'],
    [/^Reach (.+) plants to unlock \(You have (.+) plants\)$/, '达到 $1 株植物即可解锁（您有 $2 株植物）'],
    [/^You have made a total of (.+) gardens$/, '你总共建造了 $1 花园'],
    [/^You have made a total of (.+) zones$/, '你总共建造了 $1 区域'],
    [/^Next Magnitude increase at (.+) Points (.+)$/, '下一个量级增加 $1 点数 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^(.+) Plants. \((.+)\)$/, '$1 植物. \($2\)'],
    [/^([\d\.]+) sec$/, '$1 秒'],
    [/^([\d\.]+) hour$/, '$1 小时'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)e([\d\.,]+) Wildlife$/, '$1e$2 野生动物'],
    [/^([\d\.]+)e([\d\.,]+) Trees$/, '$1e$2 树'],
    [/^([\d\.]+)e([\d\.,]+) Research$/, '$1e$2 研究'],
    [/^([\d\.]+)e([\d\.,]+) Plants$/, '$1e$2 植物'],
    [/^([\d\.,]+) Useless Paperclips$/, '$1 无用的回形针'],
    [/^([\d\.,]+) Wildlife$/, '$1 野生动物'],
    [/^([\d\.,]+) Research$/, '$1 研究'],
    [/^([\d\.,]+) zones$/, '$1 区域'],
    [/^([\d\.,]+) Zone$/, '$1 区域'],
    [/^([\d\.,]+) Zones$/, '$1 区域'],
    [/^([\d\.,]+) Trees$/, '$1 树'],
    [/^([\d\.,]+) Plant$/, '$1 植物'],
    [/^([\d\.,]+) Plants$/, '$1 植物'],
    [/^([\d\.,]+) Gardens$/, '$1 花园'],
    [/^([\d\.,]+) gardens$/, '$1 花园'],
    [/^([\d\.,]+) Fish$/, '$1 鱼'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Ecosystems$/, '$1 生态系统'],
    [/^([\d\.,]+) Reclaimed Ecosystems$/, '$1 回收的生态系统'],
    [/^([\d\.,]+) Ecosystem$/, '$1 生态系统'],
    [/^([\d\.,]+) Ecosystems$/, '$1 生态系统'],
    [/^([\d\.,]+) Ecosystems and (.+) Plants$/, '$1 生态系统 和 $2 植物'],
    [/^([\d\.,]+) Ecosystem and (.+) Trees$/, '$1 生态系统 和 $2 树'],
    [/^([\d\.,]+) Ecosystem and (.+) Zones$/, '$1 生态系统 和 $2 地区'],
    [/^([\d\.,]+) Ecosystems and (.+) Zones$/, '$1 生态系统 和 $2 地区'],
    [/^([\d\.,]+) Ecosystems and (.+) Trees$/, '$1 生态系统 和 $2 树'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Next: (.+) plants$/, '下一个：$1 植物'],
    [/^Next: (.+) points$/, '下一个：$1 点数'],
    [/^Cost: (.+) Time Speed Increases. Amount: (.+).$/, '成本：$1 时间速度提升。数量：$2。'],
    [/^Cost: (.+) Trees. Amount: (.+).$/, '成本：$1 树。数量：$2。'],
    [/^Cost: (.+) Research. Amount: (.+).$/, '成本：$1 研究。数量：$2。'],
    [/^Cost: (.+) Gardens. Amount: (.+).$/, '成本：$1 花园。数量：$2。'],
    [/^Cost: (.+) Larger Wildlife. Amount: (.+).$/, '成本：$1 更大的野生动物。数量：$2。'],
    [/^Cost: (.+) Wildlife Boosters. Amount: (.+).$/, '成本：$1 野生动物助推器。数量：$2。'],
    [/^Cost: (.+). Amount: (.+).$/, '成本：$1。数量：$2。'],
    [/^Cost: (.+) Research$/, '成本：$1 研究'],
    [/^Cost: (.+) gardens$/, '成本：$1 花园'],
    [/^Cost: (.+) plants$/, '成本：$1 植物'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Cost: (.+) Fish \(Only Purchasable once Bought in \'Coral Reef\'\)$/, '成本：$1 鱼（只能在“珊瑚礁”中购买一次）'],
    [/^Cost: (.+) Fish$/, '成本：$1 鱼'],
    [/^Cost: (.+) Ecology$/, '成本：$1 生态'],
    [/^Cost: (.+) Ecosystems$/, '成本：$1 生态系统'],
    [/^Cost: (.+) wildlife$/, '成本：$1 野生动物'],
    [/^Cost: (.+) trees$/, '成本：$1 树'],
    [/^Cost: (.+) zones$/, '成本：$1 地区'],
    [/^Req: (.+) points$/, '要求：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Currently: x(.+). Currently Multiplying by (.+) When Bought$/, '当前：x$1。当前购买时乘以 $2'],
    [/^Currently: (.+)\/sec.$/, '当前：$1\/秒。'],
    [/^Currently: x(.+).$/, '当前：x$1。'],
    [/^Currently: (.+)$/, '当前：$1'],
    [/^Req: (.+) \/ (.+) trees$/, '要求：$1 \/ $2 树'],
    [/^Req: (.+) \/ (.+) plants$/, '要求：$1 \/ $2 植物'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Next: (.+) \/ (.+) trees$/, '下一个：$1 \/ $2 树'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
    [/^(.+) \/ (.+) plants$/, '$1 \/ $2 植物'],
    [/^(.+) \/ (.+) Seconds$/, '$1 \/ $2 秒'],
    [/^(.+) \/ (.+) points$/, '$1 \/ $2 点数'],
    */

]);